package com.newleaders.ac.model.pojo;

import org.joda.time.DateTime;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.enabled
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.creator_account_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer creatorAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.language
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.category
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.candidate_count_limit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer candidateCountLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.subrole
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer subrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.credit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Double credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.cv_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private Integer cvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.InputDate
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    private DateTime inputdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role
     *
     * @return the value of account.role
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role
     *
     * @param role the value for account.role
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.enabled
     *
     * @return the value of account.enabled
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.enabled
     *
     * @param enabled the value for account.enabled
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.creator_account_id
     *
     * @return the value of account.creator_account_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getCreatorAccountId() {
        return creatorAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.creator_account_id
     *
     * @param creatorAccountId the value for account.creator_account_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setCreatorAccountId(Integer creatorAccountId) {
        this.creatorAccountId = creatorAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.language
     *
     * @return the value of account.language
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.language
     *
     * @param language the value for account.language
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.category
     *
     * @return the value of account.category
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.category
     *
     * @param category the value for account.category
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.candidate_count_limit
     *
     * @return the value of account.candidate_count_limit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getCandidateCountLimit() {
        return candidateCountLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.candidate_count_limit
     *
     * @param candidateCountLimit the value for account.candidate_count_limit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setCandidateCountLimit(Integer candidateCountLimit) {
        this.candidateCountLimit = candidateCountLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.subrole
     *
     * @return the value of account.subrole
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getSubrole() {
        return subrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.subrole
     *
     * @param subrole the value for account.subrole
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setSubrole(Integer subrole) {
        this.subrole = subrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.credit
     *
     * @return the value of account.credit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.credit
     *
     * @param credit the value for account.credit
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.cv_id
     *
     * @return the value of account.cv_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public Integer getCvId() {
        return cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.cv_id
     *
     * @param cvId the value for account.cv_id
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setCvId(Integer cvId) {
        this.cvId = cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.InputDate
     *
     * @return the value of account.InputDate
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public DateTime getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.InputDate
     *
     * @param inputdate the value for account.InputDate
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    public void setInputdate(DateTime inputdate) {
        this.inputdate = inputdate;
    }
}