server:
  port: 8002

spring:
  data:
    elasticsearch:
      properties:
        host : 127.0.0.1
        port: 9300
      repositories:
        enabled: true
      cluster-name: esMaster
#      cluster-nodes: 127.0.0.1:9300


