server:
  port: 8002

spring:
  data:
    elasticsearch:
#若本地没有安装elasticsearch server开启以下注释
#      properties:
#        host : 127.0.0.1
#        port: 9300
#      repositories:
#        enabled: true
      cluster-name: lease-es-local
      cluster-nodes: 127.0.0.1:9300




