package com.newleaders.ac.model.mapper;

import com.newleaders.ac.model.pojo.Account;
import com.newleaders.ac.model.pojo.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    @Delete({
        "delete from account",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    @Insert({
        "insert into account (username, `password`, ",
        "`role`, enabled, creator_account_id, ",
        "`language`, category, ",
        "candidate_count_limit, subrole, ",
        "credit, cv_id, InputDate)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{role,jdbcType=INTEGER}, #{enabled,jdbcType=INTEGER}, #{creatorAccountId,jdbcType=INTEGER}, ",
        "#{language,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{candidateCountLimit,jdbcType=INTEGER}, #{subrole,jdbcType=INTEGER}, ",
        "#{credit,jdbcType=DOUBLE}, #{cvId,jdbcType=INTEGER}, #{inputdate,jdbcType=TIMESTAMP,typeHandler=com.newleaders.mybatis.typehandler.JodaDateTime2TimestampTypeHandler})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    @Select({
        "select",
        "id, username, `password`, `role`, enabled, creator_account_id, `language`, category, ",
        "candidate_count_limit, subrole, credit, cv_id, InputDate",
        "from account",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Mar 28 12:06:34 CST 2016
     */
    @Update({
        "update account",
        "set username = #{username,jdbcType=VARCHAR},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "`role` = #{role,jdbcType=INTEGER},",
          "enabled = #{enabled,jdbcType=INTEGER},",
          "creator_account_id = #{creatorAccountId,jdbcType=INTEGER},",
          "`language` = #{language,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=VARCHAR},",
          "candidate_count_limit = #{candidateCountLimit,jdbcType=INTEGER},",
          "subrole = #{subrole,jdbcType=INTEGER},",
          "credit = #{credit,jdbcType=DOUBLE},",
          "cv_id = #{cvId,jdbcType=INTEGER},",
          "InputDate = #{inputdate,jdbcType=TIMESTAMP,typeHandler=com.newleaders.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Account record);
}